AWSTemplateFormatVersion: 2010-09-09
Description: Fake http, ftp and sftp providers for use with Cumulus integration tests
Parameters:
  Prefix:
    Type: String
  Bucket:
    Type: String
  FtpPassword:
    Type: String
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
  NGAPProtAppInstanceMinimalPolicyName:
    Type: String
  PermissionsBoundary:
    Type: String
  Subnet:
    Type: AWS::EC2::Subnet::Id
  VpcId:
    Type: AWS::EC2::VPC::Id

Outputs:
  S3ProviderBucket:
    Value: !Ref S3ProviderBucket
    Export:
      Name: cumulus-fake-s3-provider-bucket
  S3AltProviderBucket:
    Value: !Ref S3AltProviderBucket
    Export:
      Name: cumulus-fake-s3-provider-bucket-alternate

Resources:

  S3ProviderBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${Prefix}-fake-s3-provider"

  S3AltProviderBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${Prefix}-fake-s3-provider-alternate"

  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - !Sub "arn:aws:iam::${AWS::AccountId}:policy/${NGAPProtAppInstanceMinimalPolicyName}"
      PermissionsBoundary: !Sub "arn:aws:iam::${AWS::AccountId}:policy/${PermissionsBoundary}"
      Policies:
        - PolicyName: default
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "S3:PutObject"
                Resource: !Sub "arn:aws:s3:::${Bucket}/fake-*"
              - Effect: Allow
                Action: "S3:PutObject"
                Resource: !Sub "arn:aws:s3:::${S3ProviderBucket}/*"
              - Effect: Allow
                Action: "autoscaling:SetInstanceHealth"
                Resource: "*"

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref Role

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Fake provider security group
      SecurityGroupIngress:
        - IpProtocol: "-1"
          CidrIp: "0.0.0.0/0"
          FromPort: 0
          ToPort: 0
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: "0.0.0.0/0"
          FromPort: 0
          ToPort: 0
      VpcId: !Ref VpcId

  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: false
      IamInstanceProfile: !Ref InstanceProfile
      ImageId: !Ref LatestAmiId
      InstanceMonitoring: false
      InstanceType: t3.small
      SecurityGroups:
        - !Ref SecurityGroup
      UserData:
        Fn::Base64:
          Fn::Sub: |
            #!/bin/bash -ex

            # Fetch the test data
            (cd / && mkdir cumulus && cd cumulus && git init && git remote add -f origin https://github.com/nasa/cumulus.git && git config core.sparseCheckout true && echo "packages/test-data" >> .git/info/sparse-checkout && git pull origin master)

            # Configure http
            yum install -y httpd
            sed -i 's/^Listen.*/Listen 3030/' /etc/httpd/conf/httpd.conf

            # Configure https
            yum install -y mod_ssl
            openssl req -x509 -newkey rsa:4096 -sha256 -days 3650 -nodes \
              -keyout /etc/ssl/certs/cumulus.key -out /etc/ssl/certs/cumulus.crt -outform PEM -extensions san -config \
              <(echo "[req]";
                echo distinguished_name=req;
                echo "[san]";
                echo "subjectAltName=IP:$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)";
                ) \
              -subj "/CN=`hostname`"

            cat >> /etc/httpd/conf/httpd.conf <<EOS
            Listen 4040
            <VirtualHost $(curl -s http://169.254.169.254/latest/meta-data/local-ipv4):4040>
              SSLEngine on
              SSLCertificateFile "/etc/ssl/certs/cumulus.crt"
              SSLCertificateKeyFile "/etc/ssl/certs/cumulus.key"
            </VirtualHost>
            EOS

            # Start apache server
            service httpd start

            # Stage http test data
            cp /cumulus/packages/test-data/index.html /var/www/html/
            rsync -a /cumulus/packages/test-data/pdrs /var/www/html/
            rsync -a /cumulus/packages/test-data/granules /var/www/html/

            chown -R root:root /var/www/html
            find /var/www/html -type d -exec chmod 0755 {} \;
            find /var/www/html -type f -exec chmod 0644 {} \;

            # Configure ftp
            yum install -y vsftpd

            cat > /etc/vsftpd/vsftpd.conf <<EOS
            anonymous_enable=NO
            chroot_list_enable=NO
            chroot_local_user=YES
            allow_writeable_chroot=YES
            connect_from_port_20=YES
            dirmessage_enable=YES
            listen=YES
            local_enable=YES
            local_umask=022
            pam_service_name=vsftpd
            tcp_wrappers=YES
            userlist_deny=NO
            userlist_enable=YES
            write_enable=YES
            xferlog_enable=YES
            xferlog_std_format=YES
            EOS

            echo 'testuser' > /etc/vsftpd/chroot_list
            echo 'testuser' > /etc/vsftpd/user_list

            service vsftpd restart

            mkdir /home/testuser
            useradd -M testuser
            echo '${FtpPassword}' | passwd --stdin testuser

            # Stage ftp test data
            rsync -a /cumulus/packages/test-data/pdrs /home/testuser/
            rsync -a /cumulus/packages/test-data/granules /home/testuser/

            chown -R testuser:testuser /home/testuser
            find /home/testuser -type d -exec chmod 0700 {} \;
            find /home/testuser -type f -exec chmod 0600 {} \;

            # Configure sftp
            yum install -y openssh-server

            ## Stage sftp test data
            mkdir -p /var/sftp/testdata
            rsync -a /cumulus/packages/test-data/pdrs /var/sftp/testdata
            rsync -a /cumulus/packages/test-data/granules /var/sftp/testdata

            ## use the same account (testuser) both ftp and sftp
            chown testuser:testuser /var/sftp/testdata/granules
            chown testuser:testuser /var/sftp/testdata/pdrs

            cat >> /etc/ssh/sshd_config <<EOS
            Port 22
            Match User testuser
            ForceCommand internal-sftp
            PasswordAuthentication yes
            ChrootDirectory /var/sftp/testdata
            PermitTunnel no
            AllowAgentForwarding no
            AllowTcpForwarding no
            X11Forwarding no
            EOS

            service sshd restart

            # Cleanup
            rm -rf /cumulus

            chmod 0755 $(which aws)

            # Write the fake provider IP to S3
            curl -s http://169.254.169.254/latest/meta-data/local-ipv4 |\
              aws s3 cp - s3://${Bucket}/fake-provider-ip

            # Write the fake S3 provider buckets to S3
            echo '${S3ProviderBucket}' |\
              aws s3 cp - s3://${Bucket}/fake-s3-provider-bucket

            echo '${S3AltProviderBucket}' |\
              aws s3 cp - s3://${Bucket}/fake-s3-provider-bucket-alternate

            # Copy the self-signed certificate to S3
            aws s3 cp \
              /etc/ssl/certs/cumulus.crt \
              s3://${Bucket}/fake-provider-cert.pem

            # Create the script that will stage the S3 provider's large files
            cat > /usr/local/bin/stage-s3-provider-files <<EOS
            #!/bin/sh

            dd if=/dev/zero bs=300M count=1 | aws s3 cp - s3://${S3ProviderBucket}/300M.dat
            dd if=/dev/zero bs=512M count=2 > ~/1G.dat
            dd if=/dev/zero bs=512M count=22 | aws s3 cp - s3://${S3ProviderBucket}/11G.dat

            sha256sum ~/1G.dat | awk '{printf "%s",$1}' > ~/1G.dat.sha256

            aws s3 cp ~/1G.dat s3://${S3ProviderBucket}/1G.dat
            aws s3 cp ~/1G.dat.sha256 s3://${S3ProviderBucket}/1G.dat.sha256

            rm ~/1G.dat ~/1G.dat.sha256
            EOS

            chmod 0755 /usr/local/bin/stage-s3-provider-files

            # Configure health checks
            cat > /usr/local/bin/healthcheck <<EOS
            #!/bin/sh

            curl -s -o /dev/null http://localhost:3030 \
              && curl -s -o /dev/null ftp://testuser:${FtpPassword}@localhost/granules/checksums.csv \
              || aws --region ${AWS::Region} \
                   autoscaling set-instance-health \
                   --instance-id $(curl -s http://169.254.169.254/latest/meta-data/instance-id) \
                   --health-status Unhealthy
            EOS

            chmod 0755 /usr/local/bin/healthcheck

            cat > /etc/cron.d/healthcheck <<EOS
            * * * * * root /usr/local/bin/healthcheck
            EOS

            chmod 0644 /etc/cron.d/healthcheck

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: 0
    DependsOn: S3ProviderBucket
    Properties:
      LaunchConfigurationName: !Ref LaunchConfiguration
      MinSize: "1"
      DesiredCapacity: "1"
      MaxSize: "1"
      HealthCheckGracePeriod: 60
      Tags:
        - Key: Name
          Value: FakeProvider
          PropagateAtLaunch: true
      VPCZoneIdentifier:
        - !Ref Subnet
