export const collectionsS3TableSql = (tableName: string) => `
  CREATE TABLE IF NOT EXISTS ${tableName} (
    cumulus_id INTEGER,
    name TEXT NOT NULL,
    version TEXT NOT NULL,
    sample_file_name TEXT NOT NULL,
    granule_id_validation_regex TEXT NOT NULL,
    granule_id_extraction_regex TEXT NOT NULL,
    files JSON NOT NULL,
    process TEXT,
    url_path TEXT,
    duplicate_handling TEXT,
    report_to_ems BOOLEAN,
    ignore_files_config_for_discovery BOOLEAN,
    meta JSON,
    tags JSON,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (cumulus_id),
    UNIQUE (name, version),
    CHECK (duplicate_handling IN ('error', 'replace', 'skip', 'version'))
);
`;

export const granulesS3TableSql = (tableName: string) => `
  CREATE TABLE IF NOT EXISTS ${tableName} (
    cumulus_id BIGINT,
    granule_id TEXT NOT NULL,
    status TEXT NOT NULL,
    collection_cumulus_id INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published BOOLEAN,
    duration REAL,
    time_to_archive REAL,
    time_to_process REAL,
    product_volume BIGINT,
    error JSON,
    cmr_link TEXT,
    pdr_cumulus_id INTEGER,
    provider_cumulus_id INTEGER,
    beginning_date_time TIMESTAMPTZ,
    ending_date_time TIMESTAMPTZ,
    last_update_date_time TIMESTAMPTZ,
    processing_end_date_time TIMESTAMPTZ,
    processing_start_date_time TIMESTAMPTZ,
    production_date_time TIMESTAMPTZ,
    query_fields JSON,
    \"timestamp\" TIMESTAMPTZ,
    producer_granule_id TEXT NOT NULL,
    archived BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (cumulus_id),
    UNIQUE (collection_cumulus_id, granule_id),
    CHECK (status IN ('running', 'completed', 'failed', 'queued'))
);`;
