export interface AsyncOperationRecord {
  id: string
  description: string
  operationType: string
  status: string
  output?: object
  taskArn?: string
  created_at: Date
  updated_at: Date
}

export interface CollectionRecord {
  name: string
  version: string
  process: string
  granuleIdValidationRegex: string
  granuleIdExtractionRegex: string
  files: string
  duplicateHandling?: string
  reportToEms?: boolean
  sampleFileName?: string
  url_path?: string
  ignoreFilesConfigForDiscovery?: boolean
  meta?: object
  tags?: string
  created_at: Date
  updated_at: Date
}

export interface ExecutionRecord {
  arn: string
  asyncOperationCumulusId?: number
  collectionCumulusId?: number
  parentCumulusId?: number
  cumulus_version: string
  created_at: Date
  updated_at: Date
}

/**
 * PostgresProvider
 *
 * This interface describes a Provider object in postgres compatible format that
 * is ready for write to Cumulus's postgres database instance
 */
export interface PostgresProvider {
  certificateUri?: string | null
  cmKeyId?: string | null,
  created_at?: number | null,
  cumulusId?: number | null,
  globalConnectionLimit?: number | null,
  host: string,
  name: string,
  password?: string,
  port?: number| null,
  privateKey?: string | null,
  protocol: string,
  updated_at?: number | null,
  username?: string | null,
}

/**
 * PostgresProviderRecord
 *
 * This interface describes a Provider Record that has been retrieved from
 * postgres for reading.  It differs from the PostgresProvider interface in that it types
 * the autogenerated/required fields in the Postgres database as required
 */
export interface PostgresProviderRecord extends PostgresProvider {
  created_at: number,
  updated_at: number,
  cumulusId: number,
}
