#!/usr/bin/env bash

# gleefully stolen from here
# https://github.com/wwu-numerik/scripts/blob/762ad1f6a22c3d896e8f532c506868d78988e0e0/bash/travis_wait_new.bash
set -e
set -u

TIMEOUT=$1

if [[ ${TIMEOUT} =~ ^[0-9]+$ ]]; then
    # looks like an integer, so we assume it's a timeout
    shift
else
    # default value
    TIMEOUT=20
fi

cmd="$@"

# running cmd at background
${cmd} &
pid=$!

# ping per minutes
MINUTES=0
LIMIT=${TIMEOUT}
while kill -0 $! >/dev/null 2>&1;
do
    echo -n -e " \b"  # never leave evidence

    if [ ${MINUTES} == ${LIMIT} ]; then
        exit 1;
    fi

    MINUTES=$((MINUTES + 1))

    sleep 60
done

echo command exit code $?

# exit with the status code of cmd
wait $pid
exit $?
