#!/usr/bin/env bash

if [ ! -z "${CIRCLE_USERNAME}" ]; then
    declare -A developers
    developers=( ["abarciauskas-bgse"]="aimee" \
                ["scisco"]="aj" \
                ["kkelly51"]="kk-uat-deployment" \
                ["yjpa7145"]="mth-2"
                ["jennyhliu"]="jl"
                ["laurenfrederick"]="lf")
    export DEPLOYMENT=${developers[$CIRCLE_USERNAME]}

    # if no deployment is found, user the cumulus-from-pr stack
    if [ -z "${DEPLOYMENT}" ]; then
        export DEPLOYMENT=cumulus-from-pr
    fi
fi


# if we are on release or master branch, always use cumulus-from-source stack
if [[ "$CIRCLE_BRANCH" =~ release-.* ]] || [[  "$CIRCLE_BRANCH" == 'master' ]]; then
    export DEPLOYMENT=cumulus-from-source
    export RUN_INTEGRATION=true
else
    INTEGRATION_REGEX='(\[run it\]|\[it\]|\[it run\])' # note use of [0-9] to avoid \d
    commit_message=$(git log -1 --pretty=%B)

    if [[ $commit_message =~ $INTEGRATION_REGEX ]]; then
        echo 'integration trigger was found in the commit message'
        export RUN_INTEGRATION=true
    fi
fi