locals {
  package_md5 = filemd5(var.filename)
  package_key = "${var.prefix}/lambdas/${var.function_name}-${local.package_md5}.zip"
}

# TODO Verify that this will not delete older versions of the code from S3
resource "aws_s3_bucket_object" "lambda_package" {
  bucket = var.system_bucket
  key    = local.package_key

  source = var.filename
  etag = filemd5(var.filename)

  tags = var.tags
}

resource "aws_lambda_function" "task" {
  function_name    = "${var.prefix}-${var.function_name}"
  s3_bucket        = aws_s3_bucket_object.lambda_package.bucket
  s3_key           = aws_s3_bucket_object.lambda_package.key
  source_code_hash = filebase64sha256(var.filename)
  handler          = var.handler
  role             = var.role
  runtime          = var.runtime
  timeout          = var.timeout
  memory_size      = var.memory_size

  layers = var.layers

  publish = var.enable_versioning

  environment {
    variables = var.environment_variables
  }

  vpc_config {
    subnet_ids         = var.subnet_ids
    security_group_ids = var.security_group_ids
  }

  tags = var.tags
}

# TODO Verify that this will not delete older aliases
resource "aws_lambda_alias" "default" {
  count = var.enable_versioning ? 1 : 0

  name             = "${aws_lambda_function.task.function_name}-${local.package_md5}"
  description      = "Cumulus AutoGenerated Alias | ${var.task_version}"
  function_name    = aws_lambda_function.task.function_name
  function_version = aws_lambda_function.task.version
}
