# generated by datamodel-codegen:
#   filename:  cumulus_sns_schema.json
#   timestamp: 2026-01-08T06:01:29+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional, Union

from pydantic import AwareDatetime, BaseModel, Field, RootModel


class Version(Enum):
    field_1_0 = "1.0"
    field_1_1 = "1.1"
    field_1_2 = "1.2"
    field_1_3 = "1.3"
    field_1_4 = "1.4"
    field_1_4_1 = "1.4.1"
    field_1_5 = "1.5"
    field_1_5_1 = "1.5.1"
    field_1_6_0 = "1.6.0"
    field_1_6_1_alpha_0 = "1.6.1-alpha.0"


class Status(Enum):
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"


class IngestionMetadata(BaseModel):
    catalogId: Optional[str] = Field(None, description="Identifier for catalog")
    catalogUrl: Optional[str] = Field(None, description="URL of catalog entry")


class ErrorCode(Enum):
    VALIDATION_ERROR = "VALIDATION_ERROR"
    PROCESSING_ERROR = "PROCESSING_ERROR"
    TRANSFER_ERROR = "TRANSFER_ERROR"


class Response(BaseModel):
    status: Status = Field(..., description="Successful or error.")
    ingestionMetadata: Optional[IngestionMetadata] = Field(
        None,
        description="Object defining ingestion metadata, like CMR Concept IDs, URLS, etc",
    )
    errorCode: Optional[ErrorCode] = Field(
        None, description="Error message. Success messages can be ignored."
    )
    errorMessage: Optional[str] = Field(
        None, description="The message error for the failure that occured."
    )


class DataProcessingType(Enum):
    forward = "forward"
    reprocessing = "reprocessing"


class Response1(BaseModel):
    status: Status = Field(..., description="Successful or error.")
    ingestionMetadata: Optional[IngestionMetadata] = Field(
        None,
        description="Object defining ingestion metadata, like CMR Concept IDs, URLS, etc",
    )
    errorCode: Optional[ErrorCode] = Field(
        None, description="Error message. Success messages can be ignored."
    )
    errorMessage: Optional[str] = Field(
        None, description="The message error for the failure that occured."
    )


class Type(Enum):
    data = "data"
    browse = "browse"
    metadata = "metadata"
    ancillary = "ancillary"
    linkage = "linkage"


class ChecksumType(Enum):
    SHA512 = "SHA512"
    SHA256 = "SHA256"
    SHA2 = "SHA2"
    SHA1 = "SHA1"
    md5 = "md5"


class File(BaseModel):
    type: Type = Field(
        ...,
        description="The type of file. science files (netcdf, HDF, binary) should use the 'data' type. More can be added if need and consensus demand.",
    )
    subtype: Optional[str] = Field(
        None,
        description="An optional, specific implmentation of the file::type. e.g. NetCDF for a file of type 'data'",
    )
    uri: str = Field(..., description="the URI of the file (s3://...)")
    name: str = Field(
        ..., description="The human readable filename that this file represents. "
    )
    checksumType: Optional[ChecksumType] = None
    checksum: Optional[str] = Field(None, description="Checksum of the file.")
    size: float = Field(..., description="Size, in bytes, of the file.")


class Filegroup(BaseModel):
    id: str = Field(
        ..., description="string id of the filegroup by which all files are associated."
    )
    files: List[File] = Field(
        ..., description="array of files that make up this product"
    )


class Collection(BaseModel):
    name: str = Field(..., description="collection short name.")
    version: str = Field(..., description="collection version.")


class Product(BaseModel):
    name: str = Field(..., description="Identifier/name of the product")
    dataVersion: Optional[str] = Field(None, description="Version of this product")
    dataProcessingType: Optional[DataProcessingType] = Field(
        None,
        description="The type of data processing stream that generated the product",
    )
    files: List[File] = Field(
        ..., description="array of files that make up this product"
    )
    filegroups: Optional[List[Filegroup]] = Field(
        None, description="array of filegroups that make up this product"
    )


class Product1(BaseModel):
    name: str = Field(..., description="Identifier/name of the product")
    dataVersion: Optional[str] = Field(None, description="Version of this product")
    dataProcessingType: Optional[DataProcessingType] = Field(
        None,
        description="The type of data processing stream that generated the product",
    )
    files: Optional[List[File]] = Field(
        None, description="array of files that make up this product"
    )
    filegroups: List[Filegroup] = Field(
        ..., description="array of filegroups that make up this product"
    )


class CloudNotificationMessageCnm121(BaseModel):
    version: Version = Field(..., description="The CNM Version used. e.g. '1.3'")
    receivedTime: Optional[AwareDatetime] = Field(
        None, description="Time message was received by the ingest system"
    )
    processCompleteTime: Optional[AwareDatetime] = Field(
        None, description="The time processing completed by the receiving entity."
    )
    submissionTime: AwareDatetime = Field(
        ...,
        description="The time the message was created (and presumably sent) to the publication mechanism.",
    )
    identifier: str = Field(
        ...,
        description="Unique identifier for the message as a whole. It is the senders responsibility to ensure uniqueness. This identifier can be used in response messages to provide tracability.",
    )
    collection: Union[str, Collection] = Field(
        ..., description="The collection to which these granules will belong."
    )
    provider: Optional[str] = Field(
        None,
        description="the name of the provider (e.g. SIP, SDS, etc. ) producing these files.",
    )
    trace: Optional[str] = Field(
        None, description="Information on the message or who is sending it."
    )
    response: Optional[Response] = Field(
        None,
        description="The response message type sent. Can be a success message or error message. Akin to both the PAN and PDRD",
    )
    product: Union[Product, Product1]


class Product2(BaseModel):
    name: str = Field(..., description="Identifier/name of the product")
    dataVersion: Optional[str] = Field(None, description="Version of this product")
    dataProcessingType: Optional[DataProcessingType] = Field(
        None,
        description="The type of data processing stream that generated the product",
    )
    files: List[File] = Field(
        ..., description="array of files that make up this product"
    )
    filegroups: Optional[List[Filegroup]] = Field(
        None, description="array of filegroups that make up this product"
    )


class Product3(BaseModel):
    name: str = Field(..., description="Identifier/name of the product")
    dataVersion: Optional[str] = Field(None, description="Version of this product")
    dataProcessingType: Optional[DataProcessingType] = Field(
        None,
        description="The type of data processing stream that generated the product",
    )
    files: Optional[List[File]] = Field(
        None, description="array of files that make up this product"
    )
    filegroups: List[Filegroup] = Field(
        ..., description="array of filegroups that make up this product"
    )


class CloudNotificationMessageCnm122(BaseModel):
    version: Version = Field(..., description="The CNM Version used. e.g. '1.3'")
    receivedTime: AwareDatetime = Field(
        ..., description="Time message was received by the ingest system"
    )
    processCompleteTime: AwareDatetime = Field(
        ..., description="The time processing completed by the receiving entity."
    )
    submissionTime: AwareDatetime = Field(
        ...,
        description="The time the message was created (and presumably sent) to the publication mechanism.",
    )
    identifier: str = Field(
        ...,
        description="Unique identifier for the message as a whole. It is the senders responsibility to ensure uniqueness. This identifier can be used in response messages to provide tracability.",
    )
    collection: Union[str, Collection] = Field(
        ..., description="The collection to which these granules will belong."
    )
    provider: Optional[str] = Field(
        None,
        description="the name of the provider (e.g. SIP, SDS, etc. ) producing these files.",
    )
    trace: Optional[str] = Field(
        None, description="Information on the message or who is sending it."
    )
    response: Response1 = Field(
        ...,
        description="The response message type sent. Can be a success message or error message. Akin to both the PAN and PDRD",
    )
    product: Optional[Union[Product2, Product3]] = None


class CloudNotificationMessageCnm12(
    RootModel[Union[CloudNotificationMessageCnm121, CloudNotificationMessageCnm122]]
):
    root: Union[CloudNotificationMessageCnm121, CloudNotificationMessageCnm122] = Field(
        ...,
        description="A message format to trigger or respond to processing. Version 1.2",
        title="Cloud Notification Message (cnm) 1.2 ",
    )
