# generated by datamodel-codegen:
#   filename:  input.json
#   timestamp: 2026-02-26T00:58:06+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field


class File(BaseModel):
    name: str = Field(..., description='The filename portion of path/filename')
    path: str = Field(..., description='The path portion of path/filename')
    size: Optional[int] = None
    type: Optional[str] = None
    time: Optional[int] = Field(
        None,
        description='The number of milliseconds since January 1, 1970, 00:00:00 UTC',
    )
    bucket: Optional[str] = None
    url_path: Optional[str] = None


class Granule(BaseModel):
    identifier: Optional[str] = Field(
        None,
        description='Unique identifier for a granule. It is the senders responsibility to ensure uniqueness. This identifier can be used in response messages to provide tracability.',
    )
    granuleId: str
    dataType: str
    version: str
    files: List[File]


class CMAToCNMInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    granules: List[Granule]
